baseurl = "http://zhen.org/"
languageCode = "en-us"
title = "Zen 3.1"
theme = "hyde"
copyright = "Jian Zhen. All Rights Reserved."

[Author]
	name = "Jian Zhen"

[Taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params]
	description = "Product. Data. Code"
	twitter = "https://twitter.com/zhenjl"
	linkedin = "http://linkedin.com/in/zhenjl"
	disqusShortname = "zen30"

[[menu.projects]]
	name = "sequence"
	weight = -200
	url = "https://github.com/strace/sequence"

[[menu.projects]]
	name = "surgemq"
	weight = -200
	url = "https://github.com/surgemq/surgemq"

[[menu.projects]]
	name = "zhenjl/others"
	weight = -200
	url = "https://github.com/surge"