baseurl = "http://zhen.org/"
languageCode = "en-us"
title = "Zen 3.1"
theme = "strata"
copyright = "Jian Zhen. All Rights Reserved."

[Author]
	name = "Jian Zhen"

[Taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params]
	description = "Product. Data. Code"
	twitter = "https://twitter.com/zhenjl"
	linkedin = "http://linkedin.com/in/zhenjl"
	github = "http://github.com/zhenjl"
	disqusShortname = "zen30"

[[menu.sidebar]]
	name = "Archive"
	weight = 10
	url = "/blog"

[[menu.sidebar]]
	name = "Sequence"
	weight = 20
	url = "http://sequencer.io"
